title: My GitHub Pages Site
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my GitHub Pages site.
theme: jekyll-theme-cayman
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jboychuk055.github.io/coursera-test" # the base hostname & protocol for your site

